name: Deploy Frontend to VPS

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_FRONTEND }}
          REMOTE_USER: root
          REMOTE_HOST: 5.161.88.121
          REMOTE_PATH: /var/www/carroai/frontend/
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          rsync -avz -e "ssh -i private_key -o StrictHostKeyChecking=no" dist/ $REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH
